### ISSUE TITLE
Django 1.9 deprecates IPAddressField

### ISSUE THREAD

**Issue by mvasilkov** [dmpayton/django-admin-honeypot#24]
Running **./manage.py check** on django/master yields the following:

> WARNINGS:
> admin_honeypot.LoginAttempt.ip_address: (fields.W900) IPAddressField has been deprecated. Support for it (except in historical migrations) will be removed in Django 1.9.
> 	HINT: Use GenericIPAddressField instead.

Not urgent, but worth considering, IMO.

**Comment by dmpayton** [comment]
@mvasilkov Thanks for the heads up! Migrating to GenericIPAddressField will necessitate the minimum Django version be bumped from 1.3 to 1.4, which is totally okay in my book.

**Comment by mattions** [comment]
+1 on this.

**Comment by sweaver360** [comment]
Any progress on this?

**Comment by dmpayton** [comment]
@sweaver360 I'll be taking a look at this in the next week or so, now that Django 1.9 alpha has been released.

**Comment by agusmakmun** [comment]
this awesome added against for brute force protection, but i found as same as this problem.
now i work in django 1.8, hope can support with django 1.9

**Comment by mattions** [comment]
@dmpayton any news on this one?

**Comment by mcastle** [comment]
Django-admin-honeypot is unusable now with the current version of Django 1.9.

**Comment by jherrlin** [comment]
I made a pull request for this issue.
All tests didnt pass, but i think that test is related to a template.
Output of the test is here: https://gist.github.com/jherrlin/e0861341dbb38af5c151

**Comment by dmpayton** [comment]
This has been addressed in the current develop branch. I've taken the route of removing all backwards-compatibility for Django 1.7 and below, since these versions have all reached end-of-life. Look out for a 1.0 release in the coming days. Thanks!

**Comment by stevejalim** [comment]
Thanks for the work @dmpayton!
