### ISSUE TITLE
Removed in Django 1.10 Warning

### ISSUE THREAD

**Issue by sweaver360** [dmpayton/django-admin-honeypot#38]
I recently updated to Django 1.9 and it throws this warning:

admin_honeypot\urls.py:19: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^.*$', views.AdminHoneypot.as_view(), name='index'),

I had to change ip_address to GenericIPAddressField just to get my server to run, and once it was running I got the warning above.

**Comment by dmpayton** [comment]
Done and done. Thanks!
