### ISSUE TITLE
How admin can login using Django-admin-honeypot?

### ISSUE THREAD

**Issue by avikmrr** [dmpayton/django-admin-honeypot#43]
If I am using Django-admin-honeypot then how can admin can login into the admin page. As we are trying this in the production environment then it will be difficult to change the code every time to make changes from the admin page.

**Comment by Anthropologist** [comment]
If I understand this correctly, you just need to change the real admin URL, in the docs it has '/secret' but it could be anything you want obviously.

So have honeypot take /admin, and your real admin page would be at /secret or whatever

**Comment by dmpayton** [comment]
I'm assuming the previous comment resolved the issue, and also it's been like 2 years. If not, feel free to re-open and leave a message. 👍
