### ISSUE TITLE
Breaks on Django 2.0

### ISSUE THREAD

**Issue by flexpeace** [dmpayton/django-admin-honeypot#48]
ModuleNotFoundError: No module named 'django.core.urlresolvers'

**Comment by phyxkal** [comment]
u can use django.urls

**Comment by kwill** [comment]
I think this is a duplicate of #45

**Comment by gtlambert** [comment]
@phyxkal how can we use django.urls? I'm finding the `django-admin-honeypot` breaks on Django version 2.0.2

**Comment by dmpayton** [comment]
1.1.0 has been released, now with more Django 2 compatibility! 🎉
