### ISSUE TITLE
HTML not Escaping in admin interface

### ISSUE THREAD

**Issue by ghost** [dmpayton/django-admin-honeypot#54]
For example:
`<a href="?session_key=None">None</a>`
`<a href="?path=/admin/login/?next=/admin/">/admin/login/?next=/admin/</a>`

**Comment by twlo** [comment]
I am also having this problem, and it doesn't seem to be capturing the ip address at all.

**Comment by jaap3** [comment]
There's also PR #61 and #63 :)
