### ISSUE TITLE
Emails are not sent to Admin when unauthorised accesses are made

### ISSUE THREAD

**Issue by ShyamSundhar1411** [dmpayton/django-admin-honeypot#77]
Emails are not sent to superusers' respective email even though having smtp backend and stuffs

**Comment by 9mido** [comment]
@ShyamSundhar1411

Can you show us your settings, traceback, screenshots, etc? More details would be ideal to fixing the problem.

**Comment by ShyamSundhar1411** [comment]
I actually rolled back to the previous version of the project in which  I don't have honeypot

**Comment by emb-karan** [comment]
So you must close the issue
