### ISSUE TITLE
ipware?

### ISSUE THREAD

**Issue by joetheone** [dmpayton/django-admin-honeypot#78]
Hi all,

I find it kind of crazy that this library has no built in way to pull IP addresses from anything other than `REMOTE_ADDR`. On AWS, this is always the IP of my load balancer and it makes it completely useless.

I know I can add a middleware, but why can't we be better than this? django-axes (https://github.com/jazzband/django-axes) handles this really nicely by using django-ipware(https://github.com/un33k/django-ipware) to get the IP and allowing us to configure the ipware precedence order: https://django-axes.readthedocs.io/en/latest/4_configuration.html#configuring-reverse-proxies

Can we do something similar here?

**Comment by 9mido** [comment]
Linking a related PRs:

#79, #81

**Comment by blag** [comment]
Hi, I have [forked this project](https://github.com/blag/django-admin-honeypot), merged a few PRs (including one that utilizes django-ipware to solve this exact issue), and released a [package to PyPI](https://pypi.org/project/django-admin-honeypot-updated-2021/1.2.0/). You might have better luck with my fork.

**Comment by dmpayton** [comment]
django-ipware integration has been merged into develop. 👍🏻
