### ISSUE TITLE
Django 3.1+ depreciation warning for usage of ugettext() function

### ISSUE THREAD

**Issue by dehidehidehi** [dmpayton/django-admin-honeypot#83]
Depreciation warning from Django 3.1+:
I suggest replacing all calls to ugettext() with gettext()

```
admin_honeypot\views.py:38: 
RemovedInDjango40Warning: django.utils.translation.ugettext() is deprecated in favor of django.utils.translation.gettext().
'title': _('Log in'),
```

**Comment by GitRon** [comment]
Possible duplicate to https://github.com/dmpayton/django-admin-honeypot/issues/66

**Comment by DmytroLitvinov** [comment]
I would say even drop support for Django<2.2 and support inly Python 3.6+. I am ready to provide PR with these changes (in code, in docs etc) if @dmpayton is interested and will merge it and will publish new release.

**Comment by GitRon** [comment]
@DmytroLitvinov Good idea but I fear the package is completely abandoned...

**Comment by DmytroLitvinov** [comment]
@GitRon , seems like so.
@dmpayton we can try to move it into [Jazzband organization](https://github.com/jazzband) if you don't interested in it.

**Comment by blag** [comment]
Hi, I have [forked this project](https://github.com/blag/django-admin-honeypot), merged a few PRs (including one that should solve this issue), and released a [package to PyPI](https://pypi.org/project/django-admin-honeypot-updated-2021/1.2.0/). You might have better luck with my fork.

**Comment by dmpayton** [comment]
Fixed in develop. Thanks for your patience!
