### ISSUE TITLE
Django 3.2 migration required if using BigAutoField

### ISSUE THREAD

**Issue by rob4acre** [dmpayton/django-admin-honeypot#85]
With Django 3.2 when
```
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
```
is set in set then a migration is required for admin_honeypot
```
Migrations for 'admin_honeypot':
  /usr/local/lib/python3.8/site-packages/admin_honeypot/migrations/0003_alter_loginattempt_id.py
    - Alter field id on loginattempt
```
This fails due to write permissions (at least in my application)

The relevant documentation is at: https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys

In [django celery beat](https://github.com/celery/django-celery-beat) the solution was the following : https://github.com/celery/django-celery-beat/commit/7416e22f03b19173b5ebd5cf42a7125cd0d0f051

**Comment by dmpayton** [comment]
@rob4acre Thanks for the report! This is now fixed in develop. 👍🏻

**Comment by AsinineFatuity** [comment]
HI HOW DO I ACCESS THE DEVELOP VERSION?

**Comment by vazkir** [comment]
@AsinineFatuity 

Pipenv:
```
pipenv install -e git+https://github.com/dmpayton/django-admin-honeypot.git@develop#egg=django-admin-honeypot
```

Pip:
```
pip install git+https://github.com/dmpayton/django-admin-honeypot.git@develop
```

**Comment by AsinineFatuity** [comment]
Thanks @vazkir

**Comment by usmanmukhtar** [comment]
is the PYPI package not updated? getting the warning when installing from the package.
