### ISSUE TITLE
Django 4.0 ugettext_lazy error

### ISSUE THREAD

**Issue by shawnngtq** [dmpayton/django-admin-honeypot#86]
Hi,

As per Django 4.0

> django.utils.translation.ugettext(), ugettext_lazy(), ugettext_noop(), ungettext(), and ungettext_lazy() are removed.

Here is the error:
```
...
File "/somepath/lib/python3.10/site-packages/admin_honeypot/models.py", line 2, in <module>
    from django.utils.translation import ugettext_lazy as _
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/somepath/lib/python3.10/site-packages/django/utils/translation/__init__.py)
```

Related to https://github.com/dmpayton/django-admin-honeypot/issues/83

Does anyone has an updated version of this since this hasn't been updated for sometime?

**Comment by dmpayton** [comment]
Fixed in develop. Thanks for your patience!

**Comment by nikosmichas** [comment]
Hello @dmpayton, 
Thanks for updating this to support Django 4!
Can we expect a new release with these changes soon?

**Comment by PengHao2** [comment]
The feature has removed from dingo 4.0. see https://docs.djangoproject.com/en/4.0/releases/4.0/
`django.utils.translation.ugettext(), ugettext_lazy(), ugettext_noop(), ungettext(), and ungettext_lazy() are removed.`

**Comment by iamswayam** [comment]
What about this error? I too getting the same error!! No solution until now?

**Comment by BazDev94** [comment]
What about this error? I too getting the same error!! No solution until now?

try to : 
- delete old  virtual env
- create new virtual env 
- run requirements.txt or install again your pip and upgrade Django with latest version and unistall the oldest

i hope this can help you

**Comment by Be-issenguel** [comment]
I´m getting the same error. No solution until now?

**Comment by viperthapa** [comment]
I am even getting same error .Is there is any solution ?
